import { firefox } from 'playwright-firefox'; // stealth plugin needs no outdated playwright-extra
import { authenticator } from 'otplib';
import chalk from 'chalk';
import { resolve, jsonDb, datetime, stealth, filenamify, prompt, confirm, notify, html_game_list, handleSIGINT } from './src/util.js';
import { cfg } from './src/config.js';

const screenshot = (...a) => resolve(cfg.dir.screenshots, 'luna', ...a);

const URL_CLAIM = 'https://luna.amazon.com/claims/home';

console.log(datetime(), 'started checking luna (amazon prime gaming)');

// backward compatible with existing prime-gaming claim database
const db = await jsonDb('prime-gaming.json', {});

// https://playwright.dev/docs/auth#multi-factor-authentication
const context = await firefox.launchPersistentContext(cfg.dir.browser, {
  headless: cfg.headless,
  viewport: { width: cfg.width, height: cfg.height },
  locale: 'en-US', // ignore OS locale to be sure to have english text for locators
  recordVideo: cfg.record ? { dir: 'data/record/', size: { width: cfg.width, height: cfg.height } } : undefined,
  recordHar: cfg.record ? { path: `data/record/luna-${filenamify(datetime())}.har` } : undefined,
  handleSIGINT: false, // have to handle ourselves and call context.close(), otherwise recordings from above won't be saved
});

handleSIGINT(context);

// TODO test if needed
await stealth(context);

if (!cfg.debug) context.setDefaultTimeout(cfg.timeout);

const page = context.pages().length ? context.pages()[0] : await context.newPage(); // should always exist
await page.setViewportSize({ width: cfg.width, height: cfg.height }); // workaround for https://github.com/vogler/free-games-claimer/issues/277

const notify_games = [];
let user;

try {
  await page.goto(URL_CLAIM, { waitUntil: 'domcontentloaded' }); // default 'load' takes forever

  // Wait for either sign-in button or user dropdown (indicating logged in)
  // Luna shows user's name in a dropdown when signed in, or a "Sign in" button when not
  await Promise.any([
    page.waitForSelector('button:has-text("Sign in")'),
    page.waitForSelector('a:has-text("Sign in")'),
    page.getByRole('button', { name: /^[A-Z]/ }).first().waitFor(), // user dropdown shows first name
    page.waitForSelector('[data-testid="user-menu"]'),
    page.waitForTimeout(10000), // fallback timeout
  ]);

  // ── Amazon login flow (same auth as prime-gaming, site just redirects to Amazon sign-in) ──
  while (await page.locator('button:has-text("Sign in")').or(page.locator('a:has-text("Sign in")')).count() > 0) {
    console.error('Not signed in anymore.');
    await page.locator('button:has-text("Sign in")').or(page.locator('a:has-text("Sign in")')).first().click();
    if (!cfg.debug) context.setDefaultTimeout(cfg.login_timeout); // give user some extra time to log in
    console.info(`Login timeout is ${cfg.login_timeout / 1000} seconds!`);
    if (cfg.pg_email && cfg.pg_password) console.info('Using email and password from environment.');
    else console.info('Press ESC to skip the prompts if you want to login in the browser (not possible in headless mode).');
    const email = cfg.pg_email || await prompt({ message: 'Enter email' });
    const password = email && (cfg.pg_password || await prompt({ type: 'password', message: 'Enter password' }));
    if (email && password) {
      await page.fill('[name=email]', email);
      await page.click('input[type="submit"]');
      await page.fill('[name=password]', password);
      await page.click('input[type="submit"]');
      // check for wrong credentials
      page.waitForURL('**/ap/signin**').then(async () => {
        const error = await page.locator('.a-alert-content').first().innerText();
        if (!error.trim().length) return;
        console.error('Login error:', error);
        await notify(`luna: login: ${error}`);
        await context.close();
        process.exit(1);
      });
      // handle MFA, but don't await it
      page.waitForURL('**/ap/mfa**').then(async () => {
        console.log('Two-Step Verification - enter the One Time Password (OTP), e.g. generated by your Authenticator App');
        await page.check('[name=rememberDevice]');
        const otp = cfg.pg_otpkey && authenticator.generate(cfg.pg_otpkey) || await prompt({ type: 'text', message: 'Enter two-factor sign in code', validate: n => n.toString().length == 6 || 'The code must be 6 digits!' });
        await page.locator('input[name=otpCode]').pressSequentially(otp.toString());
        await page.click('input[type="submit"]');
      }).catch(_ => { });
    } else {
      console.log('Waiting for you to login in the browser.');
      await notify('luna: no longer signed in and not enough options set for automatic login.');
      if (cfg.headless) {
        console.log('Run `SHOW=1 node luna` to login in the opened browser.');
        await context.close();
        process.exit(1);
      }
    }
    // After login, Luna redirects to the claims page
    await page.waitForURL('**/luna.amazon.com/**');
    if (!cfg.debug) context.setDefaultTimeout(cfg.timeout);
  }

  // ── Detect signed-in user ──
  // Luna nav has: button[aria-label="User dropdown and more options"] containing the user's first name
  try {
    const userBtn = page.locator('button[aria-label*="User dropdown"], button[aria-label*="more options"]').first();
    if (await userBtn.count() > 0) {
      user = await userBtn.evaluate(btn => {
        for (const child of btn.children) {
          const text = child.textContent.trim();
          if (text && text.length < 30 && !/AngleDown|NavProfile/i.test(text)) return text;
        }
        return null;
      });
    }
  } catch (_) { }
  if (!user) {
    // Fallback: find a nav button whose text is a short proper name (not a known UI label)
    const skip = new Set(['sign in', 'all', 'claim games', 'claim game', 'play now', 'play game', 'en', 'get game']);
    try {
      user = await page.evaluate((skipSet) => {
        for (const btn of document.querySelectorAll('nav button, [role="navigation"] button')) {
          const text = btn.textContent.trim();
          if (text && text.length < 20 && !skipSet.includes(text.toLowerCase())) return text;
        }
        return null;
      }, [...skip]);
    } catch (_) { }
  }
  if (!user) user = 'unknown';
  console.log(`Signed in as ${user}`);
  db.data[user] ||= {};

  // ── Navigate to "Claim games" tab ──
  // The page has tabs: "All", "Claim games", "Play Now"
  // Click "Claim games" to filter to only claimable games
  const claimGamesTab = page.getByRole('button', { name: 'Claim games' }).or(page.locator('button:has-text("Claim games")'));
  if (await claimGamesTab.count() > 0) {
    await claimGamesTab.first().click();
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000); // allow cards to render
  }

  // ── Scroll to load all game cards ──
  // Scroll the page to ensure all game cards are loaded
  let previousHeight = 0;
  for (let i = 0; i < 10; i++) {
    const currentHeight = await page.evaluate(() => document.documentElement.scrollHeight);
    if (currentHeight === previousHeight) break;
    previousHeight = currentHeight;
    await page.keyboard.press('End');
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(2000);
  }
  // Scroll back to top
  await page.keyboard.press('Home');
  await page.waitForTimeout(500);

  // ── Collect claimable games ──
  // Each game card has a heading with the title and a nested "Claim <title>" link.
  // Target the inner claim links specifically to get clean titles and avoid duplicates.
  const claimLinks = await page.locator('a[href*="/claims/"]').filter({ hasText: /^Claim /i }).all();

  const seenUrls = new Set();
  const games = [];
  for (const link of claimLinks) {
    const href = await link.getAttribute('href');
    if (!href || !href.includes('/claims/')) continue;
    const url = 'https://luna.amazon.com' + href.split('?')[0];
    if (seenUrls.has(url)) continue;
    seenUrls.add(url);

    // The inner claim link has text like "Claim Palindrome Syndrome: Escape Room"
    // or a nearby heading has the clean title
    let title;
    try {
      // First try: get the heading from the parent card element
      const heading = link.locator('xpath=ancestor::*[.//h2 or .//h3]').first().locator('h2, h3').first();
      if (await heading.count() > 0) {
        title = await heading.innerText();
      }
    } catch (_) { }
    if (!title) {
      // Fallback: extract from "Claim <title>" link text
      const linkText = await link.innerText().catch(_ => '');
      title = linkText.replace(/^Claim\s+/i, '').replace(/\s*Claim game\s*$/i, '').trim();
    }
    if (!title) {
      title = href.split('/claims/')[1]?.split('/')[0]?.replace(/-/g, ' ') || 'Unknown';
    }

    // Detect store from URL slug: "-gog" suffix = GOG, "-epic" suffix = Epic Games
    const slug = href.split('/claims/')[1]?.split('/')[0] || '';
    let store = 'amazon';
    if (slug.endsWith('-gog')) store = 'gog.com';
    else if (slug.endsWith('-epic')) store = 'epic';

    games.push({ title, url, href, store });
  }

  console.log(`\nNumber of free claimable games: ${games.length}`);
  for (const g of games) {
    console.log(` - ${g.title} (${g.store})`);
  }

  // ── Claim each game ──
  for (const game of games) {
    const { title, url, store } = game;
    console.log('\nCurrent free game:', chalk.blue(title), `(${store})`);

    if (db.data[user][title]?.status === 'claimed' || db.data[user][title]?.status === 'claimed and redeemed') {
      console.log('  Already claimed in a previous run, skipping.');
      continue;
    }

    if (cfg.dryrun) {
      console.log('  DRYRUN: would claim', title);
      continue;
    }
    if (cfg.interactive && !await confirm()) continue;

    // Navigate to the game detail page
    await page.goto(url, { waitUntil: 'domcontentloaded' });
    if (cfg.debug) await page.pause();

    // Look for the "Get game" button on the detail page
    const getGameBtn = page.getByRole('button', { name: /Get game/i })
      .or(page.locator('button:has-text("Get game")'));
    const claimBtn = page.getByRole('button', { name: /Claim/i })
      .or(page.locator('button:has-text("Claim")'));

    db.data[user][title] ||= { title, time: datetime(), url, store };
    const notify_game = { title, url };
    notify_games.push(notify_game);

    try {
      // Wait for the main CTA button to appear
      const cta = getGameBtn.or(claimBtn);
      await cta.first().waitFor({ timeout: cfg.timeout });

      // Check if already claimed (button might be disabled or show "Claimed" / success state)
      const ctaText = await cta.first().innerText();
      if (/already|claimed|owned/i.test(ctaText)) {
        console.log('  Already claimed!');
        db.data[user][title].status = 'existed';
        notify_game.status = 'existed';
        await page.screenshot({ path: screenshot(`${filenamify(title)}.png`) });
        continue;
      }

      // Click the "Get game" or "Claim" button
      await cta.first().click();

      // Wait for the result: success confirmation, GOG code, or account linking prompt
      await page.waitForTimeout(3000); // allow time for the claim to process

      // Check for success, codes, or errors
      const pageContent = await page.content();

      // Check for account linking requirement
      if (/link.*(account|game)/i.test(pageContent) && await page.locator('text=/link.*account/i').count() > 0) {
        console.error(`  Account linking is required to claim this offer on ${store}!`);
        notify_game.status = `failed: need account linking for ${store}`;
        db.data[user][title].status = 'failed: need account linking';
      } else {
        // Claimed successfully
        db.data[user][title].status = 'claimed';

        // Check for redeem codes (GOG games show a code after claiming)
        const codeInput = page.locator('input[type="text"][readonly], input[type="text"][value]').first();
        const codeText = page.locator('text=/[A-Z0-9]{4,5}-[A-Z0-9]{4,5}-[A-Z0-9]{4,5}/').first();

        let code = null;
        try {
          if (await codeInput.count() > 0) {
            code = await codeInput.inputValue();
          } else if (await codeText.count() > 0) {
            const codeMatch = (await codeText.innerText()).match(/[A-Z0-9]{4,5}-[A-Z0-9]{4,5}-[A-Z0-9]{4,5}/);
            if (codeMatch) code = codeMatch[0];
          }
        } catch (_) { }

        if (code) {
          console.log('  Code to redeem game:', chalk.blue(code));
          db.data[user][title].code = code;

          const redeem = {
            'gog.com': 'https://www.gog.com/redeem',
            'microsoft store': 'https://account.microsoft.com/billing/redeem',
            xbox: 'https://account.microsoft.com/billing/redeem',
            'legacy games': 'https://www.legacygames.com/primedeal',
          };
          const redeemUrl = store in redeem ? (store === 'gog.com' ? `${redeem[store]}/${code}` : redeem[store]) : null;
          if (redeemUrl) console.log('  URL to redeem game:', redeemUrl);

          // Auto-redeem GOG codes if configured
          if (cfg.pg_redeem && store === 'gog.com') {
            console.log(`  Trying to redeem ${code} on ${store} (need to be logged in)!`);
            const page2 = await context.newPage();
            let redeem_action = 'redeem';
            try {
              await page2.goto(redeem[store], { waitUntil: 'domcontentloaded' });
              await page2.fill('#codeInput', code);
              const r1 = page2.waitForResponse(r => r.request().method() == 'GET' && r.url().startsWith('https://redeem.gog.com/'));
              await page2.click('[type="submit"]'); // click Continue
              const r1t = await (await r1).text();
              const reason = JSON.parse(r1t).reason;
              if (reason?.includes('captcha')) {
                redeem_action = 'redeem (got captcha)';
                console.error('  Got captcha; could not redeem!');
              } else if (reason == 'code_used') {
                redeem_action = 'already redeemed';
                console.log('  Code was already used!');
              } else if (reason == 'code_not_found') {
                redeem_action = 'redeem (not found)';
                console.error('  Code was not found!');
              } else {
                redeem_action = 'redeemed?';
                console.debug(`  Response 1: ${r1t}`);
                const r2 = page2.waitForResponse(r => r.request().method() == 'POST' && r.url().startsWith('https://redeem.gog.com/'));
                await page2.click('[type="submit"]'); // click Redeem
                const r2t = await (await r2).text();
                const reason2 = JSON.parse(r2t).reason;
                if (r2t == '{}') {
                  redeem_action = 'redeemed';
                  console.log('  Redeemed successfully.');
                  db.data[user][title].status = 'claimed and redeemed';
                } else if (reason2?.includes('captcha')) {
                  redeem_action = 'redeem (got captcha)';
                  console.error('  Got captcha; could not redeem!');
                } else {
                  console.debug(`  Response 2: ${r2t}`);
                  console.log('  Unknown Response 2 - please check.');
                }
              }
            } catch (err) {
              console.error('  Redeem error:', err.message);
              redeem_action = 'redeem (error)';
            }
            if (cfg.debug) await page2.pause();
            await page2.close();
            notify_game.status = `<a href="${redeemUrl}">${redeem_action}</a> ${code} on ${store}`;
          } else if (redeemUrl) {
            notify_game.status = `<a href="${redeemUrl}">redeem</a> ${code} on ${store}`;
          } else {
            notify_game.status = `claimed on ${store} (code: ${code})`;
          }
        } else {
          notify_game.status = `claimed on ${store}`;
        }
      }

      // save screenshot of the result
      await page.screenshot({ path: screenshot(`${filenamify(title)}.png`), fullPage: true });
    } catch (error) {
      console.error(`  Error claiming ${title}:`, error.message);
      db.data[user][title].status = 'error';
      notify_game.status = `error: ${error.message.split('\n')[0]}`;
      await page.screenshot({ path: screenshot('errors', `${filenamify(title)}.png`), fullPage: true });
    }
  }

  // Take a summary screenshot if we claimed anything
  if (notify_games.length) {
    await page.goto(URL_CLAIM, { waitUntil: 'domcontentloaded' });
    if (await claimGamesTab.count() > 0) {
      await claimGamesTab.first().click();
      await page.waitForLoadState('networkidle');
    }
    const p = screenshot(`${filenamify(datetime())}.png`);
    await page.screenshot({ path: p, fullPage: true });
  }
} catch (error) {
  process.exitCode ||= 1;
  console.error('--- Exception:');
  console.error(error);
  if (error.message && process.exitCode != 130) notify(`luna failed: ${error.message.split('\n')[0]}`);
} finally {
  await db.write(); // write out json db
  if (notify_games.length) {
    notify(`luna (${user}):<br>${html_game_list(notify_games)}`);
  }
}
if (page.video()) console.log('Recorded video:', await page.video().path());
await context.close();
